# Generated by Django 2.1.5 on 2019-01-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSDM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='DATETIME')),
                ('devid', models.CharField(blank=True, max_length=255, null=True, verbose_name='DEVID')),
                ('val_power', models.IntegerField(blank=True, null=True, verbose_name='POWER')),
            ],
        ),
    ]
