# Generated by Django 2.1.5 on 2019-01-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectdata', '0002_datasdm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasdm',
            name='val_power',
        ),
        migrations.AddField(
            model_name='datasdm',
            name='val1',
            field=models.IntegerField(blank=True, null=True, verbose_name='PHASE-1'),
        ),
        migrations.AddField(
            model_name='datasdm',
            name='val2',
            field=models.IntegerField(blank=True, null=True, verbose_name='PHASE-2'),
        ),
        migrations.AddField(
            model_name='datasdm',
            name='val3',
            field=models.IntegerField(blank=True, null=True, verbose_name='PHASE-3'),
        ),
    ]
